### ISSUE TITLE
[FRAMEWORK] Agente Cultural | Inscrição em edital | Checklist de documentação (task 25)

### ISSUE THREAD

**Issue by emillecatarine** [RedeMapas/mapas#196]
**Escopo:** 

Uma das solicitações priorizadas pelo MinC foi o checklist de documentação para os agentes culturais, que os auxilia a verificar se toda a documentação necessária foi anexada na fase de avaliação documental. Esse checklist visa diminuir as possibilidades de erro e, consequentemente, aumentar a taxa de aprovações e diminuir possíveis aberturas de recurso, tornando o processo mais curto e fácil tanto para agente quanto para gestor cultural.

**Tarefas:** 
- [ ] Verificar/mapear se checklist de documentação terá documentação padrão
- [ ]  Verificar se, além da documentação padrão (caso houver), o checklist de documentação permitirá novas inclusões
- [ ]  Prototipar telas
- [ ]  Validar telas internamente (design)
- [ ]  Validar telas com Uirá e MinC

⚠️ Essa issue se relaciona com a issue ??? da jornada do gestor cultural.

**Comment by emillecatarine** [comment]
@drabelodesign imagino que o gestor cultural terá um papel aqui definindo determinada documentação para o agente cultural, se não for sempre padrão. Se for o caso, necessitará de ajustes no framework e uma nova issue no fluxo do gestor cultural pra tratar disso nos protótipos. Mas, antes de criar tudo isso, você sabe me responder se essa documentação vai ser sempre a mesma, ou varia de oportunidade pra oportunidade?

Se não souber responder, posso buscar essa resposta com Uirá/Minc ˆˆ

**Comment by RaniGub** [comment]
O time de design está realizando uma curadoria de issues... entendemos que as novas trarão o escopo das anteriores quando for oportuno.
