### ISSUE TITLE
[FRAMEWORK] Agente Cultural | Inscrição em edital | Cadastro do agente cultural individual | Organizações (task 24)

### ISSUE THREAD

**Issue by emillecatarine** [RedeMapas/mapas#239]
## *Objetivo*
Eu Como agente cultural  
Quero visualizar minha propriedade/participação em organizações
Para que eu possa visualizar e/ou gerenciar as organizações que participo, além de poder criar novas organizações

## *Contexto*
É importante que o usuário tenha uma visualização geral das organizações que participa, além de poder gerenciar as organizações que faz parte (alterar informações, gerenciar administradores, convidar novos membros...). Para isso, será criada uma seção para visualização/gerenciamento de organizações.

## *Escopo do Time*
- [x] Mapear informações importantes para a visualização geral das organizações
- [ ] Editar / validar telas de acordo com instrução normativa da PNAB (essa demanda caiu)
- [x] Prototipar telas
- [x] Validar telas internamente (design)
- [x] Validar telas MinC e Uirá

## **Escopo TEC**
- [ ] #263 
- [ ] #267
- [ ] #268
- [ ] #269
- [ ] #270
- [ ] #271

## *Critérios de Aceitação*
Se houverem dúvidas, consultar Emille.

## *Observações*
[Link do figma](https://www.figma.com/design/HkR1qdfHPn4riffcBBOQwR/Prot%C3%B3tipos-%7C-Prioriza%C3%A7%C3%B5es?node-id=351-2954&t=xgt2yTVZSpmzW2zX-4)

**Comment by emillecatarine** [comment]
@vicmagpac @lpirola telas liberadas para desenvolvimento! :)
