### ISSUE TITLE
[ROADMAP] Agente Cultural | Páginas Públicas | Perfil do Agente Cultural

### ISSUE THREAD

**Issue by juscoton** [RedeMapas/mapas#254]
## *Objetivo*
A página Pública do Agente Cultural consiste na página de perfil do Agente, que terá acesso público para quem quiser pesquisar por um agente e/ou olhar suas características, informações e saber em quais projetos culturais está envolvido. Funcionará como um Perfil de Rede Social (visualização).

## *Telas*
#- [ ] Perfil do Agente
- [ ] Selos do Agente
- [ ] Administradores do Agente
- [ ] Organizações do Agente
- [ ] Documentos do Agente
- [ ] Agenda (eventos)
- [ ] Propriedades do Agente
- [ ] Indicadores

## *Observações*
Links da estruturação dessa Task no Roadmap:
https://www.figma.com/board/181VOj4DVixEuGyKjfQeXT/RoadMap%2C-Fluxo-de-Fomento-e-Banco-de-Problemas?node-id=1581-7613&t=063GycG4rSXIgIvZ-1
