### ISSUE TITLE
Criar documentação de como contribuir

### ISSUE THREAD

**Issue by vicmagpac** [RedeMapas/mapas#59]
### Tasks

- [x] Atualizar o README para referenciar os templates abaixo
- [x] Issues template (feature, bugs)
- [x] Pull request template

### ReferÊncias

https://github.com/nodejs/nodejs.org
